[package]
name = "rand_threefry"
version = "0.1.0"
authors = ["Justin Gullingsrud <justinrocks@gmail.com>"]

[dependencies]
rand_core = "0.3.0"

[dev-dependencies]
criterion = "0.1.2"

[[bench]]
name = "threefry"
harness = false
